class DocumentationAgent:
    def draft_mou(self, parties, project, terms):
        return (
            f"Memorandum of Understanding\n\n"
            f"Between: {parties}\nProject: {project}\n\n"
            f"Terms: {terms}\n\n"
            "This document is generated by the Partnership Platform."
        )

    def draft_letter(self, recipient, subject, content):
        return (
            f"To: {recipient}\nSubject: {subject}\n\n"
            f"{content}\n\n"
            "Best regards,\nPartnership Platform"
        )
